# OpenCV的imread（）函数和imwrite()函数能支持各种静态图像文件格式

In [1]:
import numpy as np
import cv2

In [2]:
img = np.array([[0,0,0],
               [0,0,0],
               [0,0,0]], dtype=np.uint8) # 每个像素由一个8位整数来表示，即每个像素的范围位0-255

In [3]:
img = cv2.cvtColor(img, cv2.COLOR_GRAY2BGR) # 讲灰度图转化为brg彩色图

In [4]:
print(img)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [5]:
img = np.zeros((3,3), dtype=np.uint8)
print(img.shape) # 可以通过shape来查看图片的结构，会返回行和列，如果有一个以上的通道，还会返回通道数

(3, 3)


## 读取一种图片文件，将其保存为另一种格式

In [6]:
image = cv2.imread('myPic.jpg')
cv2.imwrite('myPic.png', image) # 将jpg的图片格式转化位png格式的图片

True

In [7]:
print(image.shape)

(1200, 1600, 3)


## 大多数常用的OpenCV函数都在cv2模块里，python模块被称为cv2

## 在默认情况下，即使图片为灰度格式，imread()函数也会返回BGR格式图像

In [8]:
img_new = cv2.imread('myPic.jpg', cv2.IMREAD_GRAYSCALE) # 将彩色图以灰度图的形式读入，并保存为灰度图
cv2.imwrite('gray_pic.png',img_new)
print(img_new.shape)

(1200, 1600)


In [9]:
print(img_new[0,0])

41


In [10]:
img2 = cv2.imread('gray_pic.png') # 将灰度图以彩色图读入，返回BGR格式
cv2.imwrite('bgr.png', img2)
print(img2.shape)

(1200, 1600, 3)


In [11]:
print(img2[0,0])

[41 41 41]


## bmp格式要求每个通道有8位，而png允许每个通道有8位或16位

## 若一幅图像的每个通道位8位，可以将其显示转换位标准的一维Python bytearray格式

In [12]:
byteArray = bytearray(img2)

In [13]:
bgrImage = np.array(byteArray).reshape(1200, 1600, 3) # 将含有随机字节的bytearray转化位BGR图像，灰度图同样
print(bgrImage.shape)

(1200, 1600, 3)


In [14]:
import os

In [15]:
randomByteArray = bytearray(os.urandom(120000)) # make an array of 120000 random bytes
flatNumpyArray = np.array(randomByteArray)

In [16]:
grayImage = flatNumpyArray.reshape(300, 400) # convert the array to make a 400*300 grayscale image
cv2.imwrite('RandomGray.png', grayImage) # reshape的形状是高度在前，宽度在后
print(grayImage.shape) # shape如果图像是单色或灰度，将不包含通道值

(300, 400)


In [17]:
bgrImage = flatNumpyArray.reshape(100, 400, 3) # convert the array to make a 400*100 color imgae.
cv2.imwrite('RandomColor.png', bgrImage)
print(bgrImage.shape)

(100, 400, 3)


- 使用np.random.randint(0, 256, 120000).reshape(300, 400)也能直接（并且更高效地）随机生成Numpy数组
- os.urandom函数唯一的理由是该语句有助于展示原始字节的转换

## 使用numpy.array访问图像数据

In [18]:
img3 = cv2.imread('myPic.png')

In [19]:
print(img3.shape)

(1200, 1600, 3)


In [20]:
print(img3.item(150, 150, 0)) # 第三个参数位bgr通道，分别位0,1，2

195


In [21]:
img3.itemset((150, 150, 0), 255) # 设置某个像素点的值
print(img3.item(150, 150, 0))

255


In [22]:
img4 = cv2.imread('myPic.png')
img4[:,:,1] = 0 # 将图像G通道的所有值设置为0
cv2.imwrite('lossG.png', img4) # 此时彩色图像只要b,r两个通道有值

True

## 提取图像中的某一块

In [23]:
img5 = cv2.imread('myPic.png')
print(img5.shape)

(1200, 1600, 3)


In [24]:
my_roi = img5[0:100, 0:100] # 提取左上角100*100大小的感兴趣区域
print(my_roi.shape)
cv2.imwrite('my_roi.png', my_roi)

(100, 100, 3)


True

In [25]:
print(img5.size) # 指图像像素的大小

5760000


In [26]:
print(img5.dtype) # 指图像的数据类型

uint8


## 在窗口显示图像

In [30]:
cv2.imshow('my image', img5) # 第一个参数为自己给图像显示取的名字
cv2.waitKey(1000)
cv2.destroyAllWindows() # 释放由OpenCV创建的所有窗口1